"""Change considering_reason to Text type

Revision ID: d0bbcf5a826f
Revises: 
Create Date: 2025-04-30 15:36:52.945311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bbcf5a826f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bootcamps', schema=None) as batch_op:
        batch_op.alter_column('batch_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('recruitment_start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('recruitment_end_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('considering_reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('last_contact_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('students_phone_key', type_='unique')
        batch_op.create_index('idx_student_phone_batch', ['phone', 'batch_number'], unique=True, postgresql_where=sa.text("phone != ''"))
        batch_op.create_foreign_key(None, 'bootcamps', ['bootcamp_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('idx_student_phone_batch', postgresql_where=sa.text("phone != ''"))
        batch_op.create_unique_constraint('students_phone_key', ['phone'])
        batch_op.alter_column('last_contact_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('considering_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('bootcamps', schema=None) as batch_op:
        batch_op.alter_column('recruitment_end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('recruitment_start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('batch_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
